export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_LOADING = 'SET_LOADING';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';